feat(grid): fix issue with live-editing Related #2025
There is an issue with live-editing.
When the branch is use for the Angular Samples,
the live-editing throws:
'generate-live-editing' errored:
ReferenceError: navigator is not defined.

The constants used for checking the user's browser
are replaced with functions.